export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS';
export const USER_AUTHENTICATE_FAILURE = 'USER_AUTHENTICATE_FAILURE';
export const USER_CREATE = 'USER_CREATE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const TASK_CREATE = 'TASK_CREATE';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAILURE = 'TASK_CREATE_FAILURE';
export const TASK_GET = 'TASK_GET';
export const TASK_GET_SUCCESS = 'TASK_GET_SUCCESS';
export const TASK_GET_FAILURE = 'TASK_GET_FAILURE';
export const TASK_GET_ALL = 'TASK_GET_ALL';
export const TASK_GET_ALL_SUCCESS = 'TASK_GET_ALL_SUCCESS';
export const TASK_GET_ALL_FAILURE = 'TASK_GET_ALL_FAILURE';
export const TASK_DELETE = 'TASK_DELETE';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAILURE = 'TASK_DELETE_FAILURE';
export const TASK_EDIT = 'TASK_EDIT';
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
export const TASK_EDIT_FAILURE = 'TASK_EDIT_FAILURE';
export const TASK_CHANGE_STATUS = 'TASK_CHANGE_STATUS';
export const TASK_CHANGE_STATUS_SUCCESS = 'TASK_CHANGE_STATUS_SUCCESS';
export const TASK_CHANGE_STATUS_FAILURE = 'TASK_CHANGE_STATUS_FAILURE';




